apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  # Replace 'root' and 'password' with base64 encoded values: echo -n 'your_value' | base64
  MINIO_ROOT_USER: root
  MINIO_ROOT_PASSWORD: password
