name: Test MinIO Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    # Step 3: Load environment variables from resources/local.env
    - name: Load environment variables
      run: |
        set -a
        source resources/local.env
        set +a

    # Step 4: Set up Docker
    - name: Run MinIO Docker container
      run: |
        docker run -d \
          -p 9000:9000 \
          -e "MINIO_ACCESS_KEY=admin" \
          -e "MINIO_SECRET_KEY=password" \
          --name minio \
          minio/minio server /data

    # Step 5: Install the current package
    - name: Install package using pip
      run: |
        pip install --upgrade pip
        pip install .

    # Step 6: Run Python tests
    - name: Run Python tests
      run: |
        python tests/test.py

